sitemap_url: "https://www.realestate.co.nz/sitemap.xml"
properties_url: "https://platform.realestate.co.nz/search/v1/properties/"
property_table: "data/Property.csv"
valuation_table: "data/Valuation.csv"
sale_table: "data/Sale.csv"
region_table: "data/Region.csv"
sitemap_table: "maps/categorized_sitemap.csv"
regional_map: "maps/Regional Councils.json"